# Generated by Django 6.0.5 on 2026-05-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalemissionrow',
            name='activity_end_date',
            field=models.DateField(blank=True, help_text='End of the billing or activity period', null=True),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='activity_start_date',
            field=models.DateField(blank=True, help_text='Start of the billing or activity period', null=True),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='co2e_kg',
            field=models.FloatField(blank=True, help_text='Calculated CO₂ equivalent in kilograms', null=True),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='emission_factor',
            field=models.FloatField(blank=True, help_text='Conversion factor used, e.g. 0.82 kgCO2e/kWh', null=True),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='emission_factor_source',
            field=models.CharField(blank=True, default='', help_text="Origin of the factor, e.g. 'DEFRA 2024', 'EPA eGRID 2023'", max_length=255),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='facility_code',
            field=models.CharField(blank=True, default='', help_text='Source-system identifier: SAP plant code, utility meter ID, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='facility_name',
            field=models.CharField(blank=True, default='', help_text="Human-readable site name, e.g. 'Mumbai HQ'", max_length=255),
        ),
        migrations.AddField(
            model_name='universalemissionrow',
            name='sub_category',
            field=models.CharField(blank=True, default='', help_text='Source-specific sub-type, e.g. flight_short_haul, diesel, grid_electricity', max_length=50),
        ),
    ]
